export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
